apiVersion: v1
kind: Pod
metadata:
  name: nginx1
  namespace: demo
  annotations:
    description: "NGINX app"
    createdBy: "Demo team"
    prometheus.io: "true"
spec:
  containers:
  - name: nginx
    image: nginx
