apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: samples.cache.example.com
spec:
  group: cache.example.com
  names:
    kind: Sample
    plural: samples
    singular: sample
    shortNames:
      - sam
  scope: Namespaced
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                size:
                  type: integer
                  description: Number of Sample instances
            status:
              type: object
              properties:
                nodes:
                  type: array
                  items:
                    type: string


