apiVersion: v1
kind: Pod
metadata:
  name: static-env-pod
spec:
  containers:
  - name: app1
    image: alpine
    command: ["sh", "-c", "echo $ENV"]
    env:
    - name: ENV
      value: "production"