apiVersion: v1
kind: Pod
metadata:
  name: secret-env
spec:
  containers:
  - name: db-container
    image: dbimage
    env:
    - name: DB_USER
      valueFrom:
        secretKeyRef:
          name: db-secret
          key: username
    - name: DB_PASSWORD
      valueFrom:
        secretKeyRef:
          name: db-secret
          key: password