apiVersion: v1
kind: Pod
metadata:
  name: secret-volume
spec:
  containers:
  - name: db-container
    image: dbimage
    volumeMounts:
    - name: secret-volume
      mountPath: /etc/secrets
  volumes:
  - name: secret-volume
    secret:
      secretName: db-secret