apiVersion: v1
kind: Pod
metadata:
  name: test-vol
spec:
  containers:
  - image: webserver
    name: web-container
    volumeMounts:
    - mountPath: /cache
      name: cache-volume
  volumes:
  - name: cache-volume
    emptyDir:
      sizeLimit: 250Mi