apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: sc
  annotations:
    storageclass.kubernetes.io/is-default-class: "false"
provisioner: csi-driver.example
reclaimPolicy: Retain # default value is Delete
allowVolumeExpansion: true
mountOptions:
  - discard 
volumeBindingMode: WaitForFirstConsumer
parameters:
  guaranteedReadWriteLatency: "true" # provider-specific